# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ZenpawLabs.Skypaw
PackageVersion: 1.1.0
InstallerType: portable
UpgradeBehavior: install
Commands:
- skypaw
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zenpaw-labs/skypaw/releases/download/v1.1.0/skypaw_windows_amd64.exe
  InstallerSha256: 22467B1D10F4ECB7959F181681408A73444B4CC51EE090BA19489E79D315586D
- Architecture: arm64
  InstallerUrl: https://github.com/zenpaw-labs/skypaw/releases/download/v1.1.0/skypaw_windows_arm64.exe
  InstallerSha256: D499BE248D5A22939C2828D646FB395DCB985A4645D19182073511F35CD31B55
ManifestType: installer
ManifestVersion: 1.12.0
